import { Color3 } from '@babylonjs/core';
import { createCarMesh } from './carMesh.js';
import { api, driveSession } from './routePicker.js';
export class Multiplayer {
 constructor(base,scene){this.base=base;this.room=driveSession.room;this.opponents=new Map();this.scene=scene;this.started=!this.room;this.latest=null;this.finished=null;this.busy=false;this.lastSync=0;this.banner=document.createElement('div');this.banner.className='race-banner';this.banner.hidden=true;document.body.append(this.banner);this.offset=0;this.error='';}
 async sync(){if(this.busy||!this.room)return;this.busy=true;try{const d=await api(this.base,`/api/rooms/${this.room.code}/sync`,{token:this.room.token,ready:true,state:this.latest,finished:this.finished});this.offset=d.serverNow-Date.now();this.data=d;this.lastSuccess=Date.now();this.error='';for(const p of d.players){if(p.id===this.room.playerId)continue;let mesh=this.opponents.get(p.id);if(!mesh){mesh=createCarMesh(this.scene,{name:'opponent-'+p.id,bodyColor:Color3.FromHexString(p.color)});mesh.setEnabled(false);this.opponents.set(p.id,mesh)}if(p.state){mesh.setEnabled(true);mesh.position.set(p.state.x,0,p.state.z);mesh.rotation.y=p.state.rot*Math.PI/180}}}catch(e){this.error=e.message}finally{this.busy=false}}
 update(state){if(!this.room)return;this.latest=state;const now=Date.now();if(now-this.lastSync>150){this.lastSync=now;this.sync()}const start=this.data?.startAt;this.started=!!start&&now+this.offset>=start;this.banner.hidden=this.started&&!this.finished&&!this.error;if(!this.started){this.banner.hidden=false;this.banner.textContent=this.error?`Connection lost · ${this.error}`:start?`Race starts in ${Math.max(1,Math.ceil((start-now-this.offset)/1000))}`:`Room ${this.room.code} · Waiting for your friend to load…`}
 const absent=this.data?.players.find(p=>p.id!==this.room.playerId&&now+this.offset-p.lastSeen>8000);
 if(absent&&this.started&&!this.finished){this.banner.hidden=false;this.banner.textContent='Your friend disconnected. Waiting for reconnection…'}
 if(this.error){this.banner.hidden=false;this.banner.textContent='Connection lost. Trying to reconnect…'}
 if(this.finished&&this.data){this.banner.hidden=false;const players=this.data.players;if(players.every(p=>p.finished!==null)){const sorted=[...players].sort((a,b)=>a.finished-b.finished);this.banner.replaceChildren();const title=document.createElement('div');title.textContent=sorted[0].finished===sorted[1].finished?'A tie!':`${sorted[0].name} wins`;this.banner.append(title);for(const p of sorted){const row=document.createElement('p');row.style.fontSize='18px';row.textContent=`${p.name} · ${p.finished.toFixed(2)}s including penalties`;this.banner.append(row)}}else this.banner.textContent=`Finished · ${this.finished.toFixed(2)}s · waiting for your friend…`}
 }
}
